"""creation

Revision ID: 38c5f2b02550
Revises: 
Create Date: 2023-07-03 04:55:39.680889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c5f2b02550'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('data_creation', sa.TIMESTAMP(), nullable=True),
                    sa.Column('rubrics', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texts')
    # ### end Alembic commands ###
