"""delete by id

Revision ID: 50eb14d7b548
Revises: 898009d24f5c
Create Date: 2023-07-05 03:58:45.712190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eb14d7b548'
down_revision = '898009d24f5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
