"""psql uploading csv

Revision ID: 898009d24f5c
Revises: ad0db2789389
Create Date: 2023-07-04 05:58:28.216321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898009d24f5c'
down_revision = 'ad0db2789389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
