"""db creation

Revision ID: ad0db2789389
Revises: 38c5f2b02550
Create Date: 2023-07-03 19:01:55.965776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad0db2789389'
down_revision = '38c5f2b02550'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('date_creation', sa.TIMESTAMP(), nullable=True),
                    sa.Column('rubrics', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('texts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('data_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('rubrics', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='texts_pkey')
    )

    op.drop_table('page')
    # ### end Alembic commands ###
